# Generated by Django 4.2.2 on 2023-08-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletinboard', '0004_alter_message_author_alter_message_creation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
